spring:
  application:
    name: hello-spring-cloud-consumer
server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/, http://localhost:8002/eureka/

feign:
  circuitbreaker:
    enabled: true
  hystrix:
    enabled: true #在Feign中开启Hystrix

service-url:
  hello-spring-cloud-provider: http://hello-spring-cloud-provider