spring:
  application:
    name: hello-spring-cloud-consumer
  cloud:
    stream:
      bindings:
        custom:
          group: hello-spring-cloud-consumer
          destination: hello-spring-cloud-topic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          zkNodes: localhost
server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/

feign:
  circuitbreaker:
    enabled: true
  hystrix:
    enabled: true #在Feign中开启Hystrix

service-url:
  hello-spring-cloud-provider: http://hello-spring-cloud-provider
