server:
  port: 10001
spring:
  application:
    name: hello-spring-cloud-config-client
  config:
    import: optional:configserver:http://localhost:8901
  cloud:
    config: #Config客户端配置
      profile: dev #启用配置后缀名称
      name: application #配置文件名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/

config:
  info: default