server:
  port: 8003
spring:
  application:
    name: eureka-server-slave
eureka:
  instance:
    hostname: replica2
  client:
    serviceUrl:
      defaultZone: http://replica2:8002/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true

    register-with-eureka: true