#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/db
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  application:
    name: hello-spring-cloud-provider
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

mybatis:
  auto-mapping-behavior: none
  mapper-locations: "classpath:mapper/*.xml"
  type-aliases-package: "com.example.hellospringcloud.mapper"
  configuration:
    cache-enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8002/eureka/, http://localhost:8003/eureka/"
